import {defineType} from 'sanity'

export default defineType({
  name: 'pageSection',
  title: 'Section',
  type: 'reference',
  to: [
    {type: 'hero'},
    {type: 'heroProject'},
    {type: 'industries'},
    {type: 'textOne'},
    {type: 'textTwo'},
    {type: 'textThree'},
    {type: 'ctaText'},
    {type: 'notFound'},
    {type: 'benefits'},
    {type: 'contacts'},
    {type: 'development'},
    {type: 'ourTeam'},
    {type: 'ctaImage'},
    {type: 'faq'},
    {type: 'sliderSteps'},
    {type: 'ourClients'},
    {type: 'reviews'},
    {type: 'technologyStack'},
    {type: 'caseStudies'},
    {type: 'technologies'},
    {type: 'footer'},
    {type: 'header'},
    {type: 'ctaForm'},
    {type: 'contactUs'},
    {type: 'challenge'},
    {type: 'blockText'},
    {type: 'relatedArticles'},
    {type: 'technologiesCaseItem'},
    {type: 'imageBlock'},
    {type: 'offerings'},
  ],
})
